spring:
  application:
    name: url_shortner
  profiles:
    active:
    - local

springdoc:
  show-actuator: true

app:
  openapi:
    server-url: ${OPENAPI_SERVER_URL:http://localhost:8080}
  security:
    jwt-secret: ${JWT_SECRET}
    jwt-issuer: ${JWT_ISSUER:tanmay@localhost}
    jwt-audience: ${JWT_AUDIENCE:url_shortner}
    jwt_validity: ${JWT_VALIDITY:3600}
  rate-limit:
    login-requests-per-minute: 5
    registration-requests-per-minute: 5
    url-creation-requests-per-minute: 20
    redirect-requests-per-minute: 60
